"""Memory search tool.

Provides access to long-term memory cards generated by context summarization.
"""

from __future__ import annotations

from pathlib import Path
from typing import Any

from .base import BaseTool, ToolParameter, ToolResult
from maxagent.utils.context_summary import MemoryStore, get_project_memory_path


class MemorySearchTool(BaseTool):
    """Search long-term memories for a query."""

    name = "search_memory"
    description = "Search long-term memory cards generated from previous conversation summaries."
    parameters = [
        ToolParameter(
            name="query",
            type="string",
            description="Search query, e.g. 'GPU selection decision'",
            required=True,
        ),
        ToolParameter(
            name="top_k",
            type="integer",
            description="Maximum number of memories to return",
            required=False,
            default=5,
        ),
    ]
    risk_level = "low"

    def __init__(self, project_root: Path) -> None:
        self.project_root = project_root

    async def execute(self, **kwargs: Any) -> ToolResult:
        query: str = str(kwargs.get("query", "")).strip()
        top_k = int(kwargs.get("top_k", 5) or 5)
        store = MemoryStore(get_project_memory_path(self.project_root))
        results = store.search(query, top_k=top_k)

        if not results:
            return ToolResult(success=True, output="No relevant memories found.")

        lines = ["## Memory Search Results"]
        for i, card in enumerate(results, start=1):
            tags = f" (tags: {', '.join(card.tags)})" if card.tags else ""
            lines.append(f"{i}. [{card.type}] {card.content}{tags}")

        return ToolResult(success=True, output="\n".join(lines))
